//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/darrell/Projects/Prime/Antlr4Generation/Prime.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PrimeParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IPrimeVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] PrimeParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] PrimeParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.termSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermSeq([NotNull] PrimeParser.TermSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>listUnaryOperation</c>
	/// labeled alternative in <see cref="PrimeParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListUnaryOperation([NotNull] PrimeParser.ListUnaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forEachLeftTerm</c>
	/// labeled alternative in <see cref="PrimeParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachLeftTerm([NotNull] PrimeParser.ForEachLeftTermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forEachRightTerm</c>
	/// labeled alternative in <see cref="PrimeParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachRightTerm([NotNull] PrimeParser.ForEachRightTermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binaryOperation</c>
	/// labeled alternative in <see cref="PrimeParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryOperation([NotNull] PrimeParser.BinaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>atom</c>
	/// labeled alternative in <see cref="PrimeParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] PrimeParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numericUnaryOperation</c>
	/// labeled alternative in <see cref="PrimeParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericUnaryOperation([NotNull] PrimeParser.NumericUnaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>integer</c>
	/// labeled alternative in <see cref="PrimeParser.atomTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger([NotNull] PrimeParser.IntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>negativeInfinity</c>
	/// labeled alternative in <see cref="PrimeParser.atomTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegativeInfinity([NotNull] PrimeParser.NegativeInfinityContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>positiveInfinity</c>
	/// labeled alternative in <see cref="PrimeParser.atomTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPositiveInfinity([NotNull] PrimeParser.PositiveInfinityContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nullaryOperation</c>
	/// labeled alternative in <see cref="PrimeParser.atomTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullaryOperation([NotNull] PrimeParser.NullaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parens</c>
	/// labeled alternative in <see cref="PrimeParser.atomTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParens([NotNull] PrimeParser.ParensContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.forEachBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachBlock([NotNull] PrimeParser.ForEachBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forEachBinary</c>
	/// labeled alternative in <see cref="PrimeParser.forEachOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachBinary([NotNull] PrimeParser.ForEachBinaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forEachNumericUnary</c>
	/// labeled alternative in <see cref="PrimeParser.forEachOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachNumericUnary([NotNull] PrimeParser.ForEachNumericUnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forEachListUnary</c>
	/// labeled alternative in <see cref="PrimeParser.forEachOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachListUnary([NotNull] PrimeParser.ForEachListUnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.baseNullaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseNullaryOp([NotNull] PrimeParser.BaseNullaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.baseNumUnaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseNumUnaryOp([NotNull] PrimeParser.BaseNumUnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.baseNumBinaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseNumBinaryOp([NotNull] PrimeParser.BaseNumBinaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.baseListUnaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseListUnaryOp([NotNull] PrimeParser.BaseListUnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.baseListBinaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseListBinaryOp([NotNull] PrimeParser.BaseListBinaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.opMods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpMods([NotNull] PrimeParser.OpModsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.assignMods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignMods([NotNull] PrimeParser.AssignModsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.nullaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullaryOp([NotNull] PrimeParser.NullaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.numUnaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumUnaryOp([NotNull] PrimeParser.NumUnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.listUnaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListUnaryOp([NotNull] PrimeParser.ListUnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.binaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryOp([NotNull] PrimeParser.BinaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimeParser.outMethod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutMethod([NotNull] PrimeParser.OutMethodContext context);
}
