//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/darrell/Projects/Prime/Antlr4Generation/PrimellParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PrimellParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IPrimellParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] PrimellParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.outputSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputSpec([NotNull] PrimellParser.OutputSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.termSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermSeq([NotNull] PrimellParser.TermSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.concatRtlTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcatRtlTerm([NotNull] PrimellParser.ConcatRtlTermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>passThroughRtl</c>
	/// labeled alternative in <see cref="PrimellParser.rtlTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPassThroughRtl([NotNull] PrimellParser.PassThroughRtlContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stdAssign</c>
	/// labeled alternative in <see cref="PrimellParser.rtlTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStdAssign([NotNull] PrimellParser.StdAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forEachRightAssign</c>
	/// labeled alternative in <see cref="PrimellParser.rtlTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachRightAssign([NotNull] PrimellParser.ForEachRightAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forEachLeftAssign</c>
	/// labeled alternative in <see cref="PrimellParser.rtlTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachLeftAssign([NotNull] PrimellParser.ForEachLeftAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.binaryAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryAssign([NotNull] PrimellParser.BinaryAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forEachRightBinary</c>
	/// labeled alternative in <see cref="PrimellParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachRightBinary([NotNull] PrimellParser.ForEachRightBinaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>listUnaryOperation</c>
	/// labeled alternative in <see cref="PrimellParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListUnaryOperation([NotNull] PrimellParser.ListUnaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binaryOperation</c>
	/// labeled alternative in <see cref="PrimellParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryOperation([NotNull] PrimellParser.BinaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forEachLeftBinary</c>
	/// labeled alternative in <see cref="PrimellParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachLeftBinary([NotNull] PrimellParser.ForEachLeftBinaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>passThroughMulTerm</c>
	/// labeled alternative in <see cref="PrimellParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPassThroughMulTerm([NotNull] PrimellParser.PassThroughMulTermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>numericUnaryOperation</c>
	/// labeled alternative in <see cref="PrimellParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericUnaryOperation([NotNull] PrimellParser.NumericUnaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>forEachListUnary</c>
	/// labeled alternative in <see cref="PrimellParser.mulTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachListUnary([NotNull] PrimellParser.ForEachListUnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>integer</c>
	/// labeled alternative in <see cref="PrimellParser.atomTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger([NotNull] PrimellParser.IntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>infinity</c>
	/// labeled alternative in <see cref="PrimellParser.atomTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInfinity([NotNull] PrimellParser.InfinityContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nullaryOperation</c>
	/// labeled alternative in <see cref="PrimellParser.atomTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullaryOperation([NotNull] PrimellParser.NullaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>emptyList</c>
	/// labeled alternative in <see cref="PrimellParser.atomTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyList([NotNull] PrimellParser.EmptyListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parens</c>
	/// labeled alternative in <see cref="PrimellParser.atomTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParens([NotNull] PrimellParser.ParensContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.baseNullaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseNullaryOp([NotNull] PrimellParser.BaseNullaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.baseNumUnaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseNumUnaryOp([NotNull] PrimellParser.BaseNumUnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.baseNumBinaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseNumBinaryOp([NotNull] PrimellParser.BaseNumBinaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.baseListUnaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseListUnaryOp([NotNull] PrimellParser.BaseListUnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.baseListBinaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseListBinaryOp([NotNull] PrimellParser.BaseListBinaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.baseListNumericOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseListNumericOp([NotNull] PrimellParser.BaseListNumericOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.baseNumericListOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseNumericListOp([NotNull] PrimellParser.BaseNumericListOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.opMods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpMods([NotNull] PrimellParser.OpModsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.assignMods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignMods([NotNull] PrimellParser.AssignModsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.nullaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullaryOp([NotNull] PrimellParser.NullaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.numUnaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumUnaryOp([NotNull] PrimellParser.NumUnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.listUnaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListUnaryOp([NotNull] PrimellParser.ListUnaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.binaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryOp([NotNull] PrimellParser.BinaryOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PrimellParser.baseBinaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseBinaryOp([NotNull] PrimellParser.BaseBinaryOpContext context);
}
